myshell=bash
build:
	@echo "Building"
	gcc -Wall -g mapmaker.c net.c cleanup.c event.c init.c main.c render.c routines.c menu.c sound.c -o AGE_CLIENT -lSDL -lglut -lSDL_net -lSDL_image -lSDL_mixer -lGLU
clean:
	rm -f age

